vich_uploader:
    db_driver: orm
    mappings:
        work:
            uri_prefix: /upload/works
            upload_destination: '%kernel.project_dir%/assets/uploads/works'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer
